# Generated by Django 2.2 on 2019-10-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191013_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
