# Generated by Django 2.2 on 2019-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20191019_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=' ', max_length=15, null=True),
        ),
    ]
